### ISSUE TITLE
Feature request: add tooltips for normal capacitors

### ISSUE THREAD

**Issue by calloatti** [Tfarcenim/lootcapacitortooltips#1]
Instead of having to remember what the values are for  basic, double and octadic capacitors, how about you just add tootlips for those?

**Comment by MaxNeedsSnacks** [comment]
I think the problem with those is that their values are not embedded into the item as an NBT tag (because why would they be, they're static values), so you'd have to read the values from the xml files (and make sure to incorporate any user-overriden values)

That is... if my understanding of this whole thing is more than just "might could should"

**Comment by Tfarcenim** [comment]
the latest version has the option to display these now although idk how to make it read from the config without making it required serverside as well.

**Comment by MaxNeedsSnacks** [comment]
I'm not sure whether it's even possible lol

**Comment by calloatti** [comment]
I have never written a line of code in Java, and may be way off here, but maybe this helps?:

https://github.com/SleepyTrousers/EnderIO/wiki/API-Capacitors

https://github.com/SleepyTrousers/EnderIO/blob/37629ade042e9372c1d6df0852db775e7cb7a5f8/enderio-base/src/main/java/crazypants/enderio/base/capacitor/DefaultCapacitorData.java

It seems you can use getUnscaledValue maybe?
